#property copyright "Generated by Cursor Agent"
#property version   "1.00"
#property strict

input int               ATR_Period        = 14;
input ENUM_TIMEFRAMES   ATR_Timeframe     = PERIOD_CURRENT;
input double            ATR_Trigger       = 0.00100;
input color             Line_Color        = clrLime;
input ENUM_LINE_STYLE   Line_Style        = STYLE_SOLID;
input int               Line_Width        = 1;
input bool              Enable_Alert      = true;
input bool              Enable_Sound      = false;
input string            Sound_File        = "alert.wav";

int      g_atr_handle            = INVALID_HANDLE;
datetime g_last_bar_open_time    = 0;
int      g_atr_timeframe         = PERIOD_CURRENT;

int OnInit()
{
   g_atr_timeframe = (ATR_Timeframe == PERIOD_CURRENT) ? _Period : (int)ATR_Timeframe;
   g_atr_handle = iATR(_Symbol, (ENUM_TIMEFRAMES)g_atr_timeframe, ATR_Period);
   if(g_atr_handle == INVALID_HANDLE)
   {
      PrintFormat("Failed to create ATR handle. Error: %d", GetLastError());
      return(INIT_FAILED);
   }

   g_last_bar_open_time = iTime(_Symbol, (ENUM_TIMEFRAMES)g_atr_timeframe, 0);
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   if(g_atr_handle != INVALID_HANDLE)
   {
      IndicatorRelease(g_atr_handle);
      g_atr_handle = INVALID_HANDLE;
   }
}

void OnTick()
{
   if(g_atr_handle == INVALID_HANDLE)
      return;

   datetime bar_open_time = iTime(_Symbol, (ENUM_TIMEFRAMES)g_atr_timeframe, 0);
   if(bar_open_time <= 0 || bar_open_time == g_last_bar_open_time)
      return;

   g_last_bar_open_time = bar_open_time;

   double atr_values[2];
   ArraySetAsSeries(atr_values, true);
   int copied = CopyBuffer(g_atr_handle, 0, 1, 2, atr_values);
   if(copied != 2)
   {
      PrintFormat("Unable to copy ATR values. Copied=%d Error=%d", copied, GetLastError());
      return;
   }

   double current_atr  = atr_values[0];
   double previous_atr = atr_values[1];

   if(previous_atr <= ATR_Trigger && current_atr > ATR_Trigger)
   {
      datetime signal_time = iTime(_Symbol, (ENUM_TIMEFRAMES)g_atr_timeframe, 1);
      DrawSignalLine(signal_time);
      SendSignalAlert(signal_time, previous_atr, current_atr);
   }
}

void DrawSignalLine(const datetime signal_time)
{
   string line_name = StringFormat("ATR_UpCross_%I64d", (long)signal_time);
   if(ObjectFind(0, line_name) >= 0)
      return;

   if(!ObjectCreate(0, line_name, OBJ_VLINE, 0, signal_time, 0.0))
   {
      PrintFormat("Failed to create vertical line %s. Error: %d", line_name, GetLastError());
      return;
   }

   ObjectSetInteger(0, line_name, OBJPROP_COLOR, Line_Color);
   ObjectSetInteger(0, line_name, OBJPROP_STYLE, Line_Style);
   ObjectSetInteger(0, line_name, OBJPROP_WIDTH, Line_Width);
}

void SendSignalAlert(const datetime signal_time, const double previous_atr, const double current_atr)
{
   string message = StringFormat(
      "%s | %s ATR crossed upward trigger %.5f (%.5f -> %.5f) at %s",
      MQLInfoString(MQL_PROGRAM_NAME),
      _Symbol,
      ATR_Trigger,
      previous_atr,
      current_atr,
      TimeToString(signal_time, TIME_DATE | TIME_MINUTES)
   );

   Print(message);

   if(Enable_Alert)
      Alert(message);

   if(Enable_Sound)
      PlaySound(Sound_File);
}
