#property copyright "Generated by Cursor Cloud Agent"
#property version   "1.00"
#property strict

input ENUM_TIMEFRAMES InpAtrTimeframe = PERIOD_M1; // ATR timeframe
input int             InpAtrPeriod = 14;           // ATR period
input double          InpAtrLevel = 3.300;         // Alert level
input int             InpCheckIntervalSeconds = 5; // Timer check interval
input bool            InpSendPushNotification = true;
input bool            InpAllowOnlyCrash300And500 = true;

int    g_atrHandle = INVALID_HANDLE;
double g_previousAtr = EMPTY_VALUE;

bool SymbolIsSupported(const string symbol_name)
{
   if(!InpAllowOnlyCrash300And500)
      return true;

   if(StringFind(symbol_name, "Crash 300") >= 0)
      return true;

   if(StringFind(symbol_name, "Crash 500") >= 0)
      return true;

   return false;
}

void NotifyAtrReached(const double current_atr)
{
   string message = StringFormat(
      "ATR level reached on %s | ATR(%d) = %.3f | Level = %.3f | TF = %s",
      _Symbol,
      InpAtrPeriod,
      current_atr,
      InpAtrLevel,
      EnumToString(InpAtrTimeframe)
   );

   Print(message);
   Alert(message);

   if(InpSendPushNotification)
   {
      if(!SendNotification(message))
      {
         PrintFormat("SendNotification failed (error %d).", GetLastError());
      }
   }
}

void CheckAtrLevel()
{
   if(g_atrHandle == INVALID_HANDLE)
      return;

   double atr_values[2];
   int copied = CopyBuffer(g_atrHandle, 0, 0, 2, atr_values);
   if(copied < 1)
   {
      PrintFormat("CopyBuffer for ATR failed (error %d).", GetLastError());
      return;
   }

   double current_atr = atr_values[0];
   bool crossed_up = false;

   if(g_previousAtr == EMPTY_VALUE)
      crossed_up = (current_atr >= InpAtrLevel);
   else
      crossed_up = (g_previousAtr < InpAtrLevel && current_atr >= InpAtrLevel);

   if(crossed_up)
      NotifyAtrReached(current_atr);

   g_previousAtr = current_atr;
}

int OnInit()
{
   if(!SymbolIsSupported(_Symbol))
   {
      Print("This EA is limited to Crash 300 / Crash 500 symbols by default.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   if(InpAtrPeriod <= 0)
   {
      Print("InpAtrPeriod must be greater than zero.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   if(InpCheckIntervalSeconds < 1)
   {
      Print("InpCheckIntervalSeconds must be at least 1 second.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   g_atrHandle = iATR(_Symbol, InpAtrTimeframe, InpAtrPeriod);
   if(g_atrHandle == INVALID_HANDLE)
   {
      PrintFormat("Failed to create ATR handle (error %d).", GetLastError());
      return(INIT_FAILED);
   }

   EventSetTimer(InpCheckIntervalSeconds);
   CheckAtrLevel();
   return(INIT_SUCCEEDED);
}

void OnTimer()
{
   CheckAtrLevel();
}

void OnDeinit(const int reason)
{
   EventKillTimer();

   if(g_atrHandle != INVALID_HANDLE)
   {
      IndicatorRelease(g_atrHandle);
      g_atrHandle = INVALID_HANDLE;
   }
}
