#property copyright "Generated by Cursor Cloud Agent"
#property version   "1.00"
#property strict

input ENUM_TIMEFRAMES   ForceTimeframe      = PERIOD_CURRENT;
input int               ForceMAPeriod       = 13;
input ENUM_MA_METHOD    ForceMAMethod       = MODE_EMA;
input ENUM_APPLIED_VOLUME ForceVolumeType   = VOLUME_TICK;
input double            AlertThreshold      = -1000.0;
input color             AlertLineColor      = clrRed;
input ENUM_LINE_STYLE   AlertLineStyle      = STYLE_DASH;
input int               AlertLineWidth      = 1;

int      g_forceHandle       = INVALID_HANDLE;
bool     g_wasBelowThreshold = false;
int      g_alertCounter      = 0;

bool ReadForceIndex(double &currentValue,double &previousValue)
{
   double forceValues[];
   ArrayResize(forceValues,2);
   ArraySetAsSeries(forceValues,true);

   const int copied=CopyBuffer(g_forceHandle,0,0,2,forceValues);
   if(copied<2)
      return false;

   currentValue  = forceValues[0];
   previousValue = forceValues[1];
   return true;
}

void DrawAlertLine(datetime when)
{
   string lineName=StringFormat("FI_Alert_%s_%d",TimeToString(when,TIME_DATE|TIME_SECONDS),g_alertCounter++);
   StringReplace(lineName,":","-");
   StringReplace(lineName,".","-");

   if(!ObjectCreate(0,lineName,OBJ_VLINE,0,when,0))
   {
      PrintFormat("Failed to create vertical line '%s'. Error: %d",lineName,GetLastError());
      return;
   }

   ObjectSetInteger(0,lineName,OBJPROP_COLOR,AlertLineColor);
   ObjectSetInteger(0,lineName,OBJPROP_STYLE,AlertLineStyle);
   ObjectSetInteger(0,lineName,OBJPROP_WIDTH,AlertLineWidth);
}

void TriggerAlert(const double currentForce)
{
   const datetime triggerTime=TimeCurrent();
   const string message=StringFormat("Force Index %.2f dropped below threshold %.2f (%s, %s).",
                                     currentForce,
                                     AlertThreshold,
                                     _Symbol,
                                     EnumToString((ENUM_TIMEFRAMES)Period()));
   Alert(message);
   Print(message);
   DrawAlertLine(triggerTime);
}

int OnInit()
{
   g_forceHandle=iForce(_Symbol,ForceTimeframe,ForceMAPeriod,ForceMAMethod,ForceVolumeType);
   if(g_forceHandle==INVALID_HANDLE)
   {
      PrintFormat("Unable to create Force Index handle. Error: %d",GetLastError());
      return INIT_FAILED;
   }

   double currentForce=0.0;
   double previousForce=0.0;
   if(ReadForceIndex(currentForce,previousForce))
      g_wasBelowThreshold=(currentForce<AlertThreshold);

   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if(g_forceHandle!=INVALID_HANDLE)
      IndicatorRelease(g_forceHandle);

   Comment("");
}

void OnTick()
{
   double currentForce=0.0;
   double previousForce=0.0;
   if(!ReadForceIndex(currentForce,previousForce))
   {
      Comment("Force Index data unavailable. Waiting for more bars...");
      return;
   }

   const bool isBelowThreshold=(currentForce<AlertThreshold);
   if(isBelowThreshold && !g_wasBelowThreshold)
      TriggerAlert(currentForce);

   g_wasBelowThreshold=isBelowThreshold;

   Comment(
      StringFormat(
         "Force Index Monitor\nCurrent: %.2f\nPrevious: %.2f\nThreshold: %.2f\nStatus: %s",
         currentForce,
         previousForce,
         AlertThreshold,
         isBelowThreshold ? "Below threshold" : "Above threshold"
      )
   );
}
