#property copyright "Generated by Cursor Agent"
#property version   "1.00"
#property strict

input string             InpSymbol            = "";          // Empty = current chart symbol
input ENUM_TIMEFRAMES    InpRSITimeframe      = PERIOD_M5;   // RSI calculation timeframe
input int                InpRSIPeriod         = 14;          // RSI period
input ENUM_APPLIED_PRICE InpAppliedPrice      = PRICE_CLOSE; // RSI applied price
input double             InpTriggerRSIValue   = 30.0;        // Cross-down trigger level (0-100)
input bool               InpSendPushAlert     = true;        // Send push alert to connected MT5 device
input bool               InpShowTerminalAlert = true;        // Show terminal popup alert
input color              InpLineColor         = clrRed;      // Vertical line color
input ENUM_LINE_STYLE    InpLineStyle         = STYLE_SOLID; // Vertical line style
input int                InpLineWidth         = 1;           // Vertical line width

int      g_rsiHandle            = INVALID_HANDLE;
string   g_symbol               = "";
datetime g_lastProcessedBarTime = 0;

bool CreateSignalLine(const datetime signalTime)
{
   string lineName = StringFormat("RSI_CrossDown_%s_%I64d", g_symbol, (long)signalTime);

   if(ObjectFind(0, lineName) != -1)
      return true;

   if(!ObjectCreate(0, lineName, OBJ_VLINE, 0, signalTime, 0.0))
   {
      PrintFormat("Failed to create vertical line. Error: %d", GetLastError());
      return false;
   }

   ObjectSetInteger(0, lineName, OBJPROP_COLOR, InpLineColor);
   ObjectSetInteger(0, lineName, OBJPROP_STYLE, InpLineStyle);
   ObjectSetInteger(0, lineName, OBJPROP_WIDTH, InpLineWidth);
   ObjectSetInteger(0, lineName, OBJPROP_BACK, false);
   ObjectSetInteger(0, lineName, OBJPROP_SELECTABLE, true);
   ObjectSetInteger(0, lineName, OBJPROP_SELECTED, false);
   ObjectSetInteger(0, lineName, OBJPROP_HIDDEN, false);

   return true;
}

void NotifySignal(const string message)
{
   if(InpShowTerminalAlert)
      Alert(message);

   if(InpSendPushAlert)
   {
      ResetLastError();
      if(!SendNotification(message))
         PrintFormat("SendNotification failed. Error: %d", GetLastError());
   }

   Print(message);
}

int OnInit()
{
   if(InpTriggerRSIValue < 0.0 || InpTriggerRSIValue > 100.0)
   {
      Print("InpTriggerRSIValue must be between 0 and 100.");
      return INIT_PARAMETERS_INCORRECT;
   }

   if(InpRSIPeriod <= 1)
   {
      Print("InpRSIPeriod must be greater than 1.");
      return INIT_PARAMETERS_INCORRECT;
   }

   g_symbol = (InpSymbol == "") ? _Symbol : InpSymbol;

   if(!SymbolSelect(g_symbol, true))
   {
      PrintFormat("Could not select symbol '%s'.", g_symbol);
      return INIT_FAILED;
   }

   g_rsiHandle = iRSI(g_symbol, InpRSITimeframe, InpRSIPeriod, InpAppliedPrice);
   if(g_rsiHandle == INVALID_HANDLE)
   {
      PrintFormat("Failed to create RSI handle. Error: %d", GetLastError());
      return INIT_FAILED;
   }

   PrintFormat("Initialized for symbol=%s timeframe=%s period=%d trigger=%.2f",
               g_symbol, EnumToString(InpRSITimeframe), InpRSIPeriod, InpTriggerRSIValue);
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);
}

void OnTick()
{
   if(g_rsiHandle == INVALID_HANDLE)
      return;

   datetime closedBarTime = iTime(g_symbol, InpRSITimeframe, 1);
   if(closedBarTime <= 0 || closedBarTime == g_lastProcessedBarTime)
      return;

   g_lastProcessedBarTime = closedBarTime;

   double rsiValues[2];
   ArraySetAsSeries(rsiValues, true);
   int copied = CopyBuffer(g_rsiHandle, 0, 1, 2, rsiValues);
   if(copied != 2)
   {
      PrintFormat("CopyBuffer failed. Copied=%d Error=%d", copied, GetLastError());
      return;
   }

   double currentClosedRSI = rsiValues[0]; // Bar shift 1
   double previousClosedRSI = rsiValues[1]; // Bar shift 2

   bool crossedDown = (previousClosedRSI > InpTriggerRSIValue && currentClosedRSI <= InpTriggerRSIValue);
   if(!crossedDown)
      return;

   CreateSignalLine(closedBarTime);

   string message = StringFormat("RSI CROSS DOWN: %s (%s) RSI %.2f -> %.2f crossed below %.2f at %s",
                                 g_symbol,
                                 EnumToString(InpRSITimeframe),
                                 previousClosedRSI,
                                 currentClosedRSI,
                                 InpTriggerRSIValue,
                                 TimeToString(closedBarTime, TIME_DATE | TIME_MINUTES));
   NotifySignal(message);
}
