#property copyright "Generated by Cursor Cloud Agent"
#property version   "1.00"
#property strict

input int                InpRSIPeriod         = 14;
input double             InpTriggerLevel      = 30.0;
input ENUM_TIMEFRAMES    InpRSITimeframe      = PERIOD_CURRENT;
input ENUM_APPLIED_PRICE InpAppliedPrice      = PRICE_CLOSE;

input bool               InpEnableAlert       = true;
input bool               InpEnableNotification= false;
input bool               InpPrintToJournal    = true;

input color              InpLineColor         = clrRed;
input ENUM_LINE_STYLE    InpLineStyle         = STYLE_DOT;
input int                InpLineWidth         = 1;

int             g_rsiHandle          = INVALID_HANDLE;
ENUM_TIMEFRAMES g_activeTimeframe    = PERIOD_CURRENT;
double          g_currentRsi         = 0.0;
bool            g_stateInitialized   = false;
bool            g_wasAboveTrigger    = false;
bool            g_timerRunning       = false;
datetime        g_triggerStartTime   = 0;
long            g_triggerCount       = 0;
string          g_eaTag              = "RSI Trigger EA";

ENUM_TIMEFRAMES ResolveTimeframe()
{
   if(InpRSITimeframe == PERIOD_CURRENT)
      return (ENUM_TIMEFRAMES)Period();

   return InpRSITimeframe;
}

bool CreateRsiHandle()
{
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);

   g_activeTimeframe = ResolveTimeframe();
   g_rsiHandle = iRSI(_Symbol, g_activeTimeframe, InpRSIPeriod, InpAppliedPrice);

   if(g_rsiHandle == INVALID_HANDLE)
   {
      Print("Failed to create RSI handle. Error: ", GetLastError());
      return false;
   }

   g_stateInitialized = false;
   return true;
}

string FormatElapsed(int elapsedSeconds)
{
   int hours = elapsedSeconds / 3600;
   int mins  = (elapsedSeconds % 3600) / 60;
   int secs  = elapsedSeconds % 60;

   return StringFormat("%02d:%02d:%02d", hours, mins, secs);
}

void DrawTriggerVerticalLine(datetime triggerTime)
{
   string lineName = StringFormat("RSI_TRIGGER_VLINE_%I64d", g_triggerCount);
   if(!ObjectCreate(0, lineName, OBJ_VLINE, 0, triggerTime, 0.0))
   {
      Print("Failed to draw trigger line. Error: ", GetLastError());
      return;
   }

   ObjectSetInteger(0, lineName, OBJPROP_COLOR, InpLineColor);
   ObjectSetInteger(0, lineName, OBJPROP_STYLE, InpLineStyle);
   ObjectSetInteger(0, lineName, OBJPROP_WIDTH, InpLineWidth);
   ObjectSetInteger(0, lineName, OBJPROP_BACK, false);
}

void SendTriggerAlert(datetime triggerTime, double rsiValue)
{
   string message = StringFormat(
      "%s: RSI(%d) down-crossed %.2f on %s [%s], current RSI %.2f at %s",
      g_eaTag,
      InpRSIPeriod,
      InpTriggerLevel,
      _Symbol,
      EnumToString(g_activeTimeframe),
      rsiValue,
      TimeToString(triggerTime, TIME_DATE | TIME_SECONDS)
   );

   if(InpEnableAlert)
      Alert(message);

   if(InpEnableNotification)
      SendNotification(message);

   if(InpPrintToJournal)
      Print(message);
}

void TriggerActions(double rsiValue)
{
   datetime triggerTime = TimeCurrent();
   g_triggerCount++;
   g_timerRunning = true;
   g_triggerStartTime = triggerTime;

   DrawTriggerVerticalLine(triggerTime);
   SendTriggerAlert(triggerTime, rsiValue);
}

bool RefreshRsiAndSignals()
{
   if(g_rsiHandle == INVALID_HANDLE)
      return false;

   double rsiBuffer[];
   ArraySetAsSeries(rsiBuffer, true);

   int copied = CopyBuffer(g_rsiHandle, 0, 0, 2, rsiBuffer);
   if(copied < 2)
      return false;

   if(rsiBuffer[0] == EMPTY_VALUE || rsiBuffer[1] == EMPTY_VALUE)
      return false;

   g_currentRsi = rsiBuffer[0];
   double prevRsi = rsiBuffer[1];

   if(!g_stateInitialized)
   {
      g_wasAboveTrigger = (prevRsi > InpTriggerLevel);
      g_stateInitialized = true;
   }

   if(g_wasAboveTrigger && g_currentRsi <= InpTriggerLevel)
   {
      TriggerActions(g_currentRsi);
      g_wasAboveTrigger = false;
   }
   else if(g_currentRsi > InpTriggerLevel)
   {
      g_wasAboveTrigger = true;
   }

   return true;
}

void UpdateChartDisplay()
{
   string timerState = "Not started";
   if(g_timerRunning)
   {
      int elapsed = (int)MathMax(0, (int)(TimeCurrent() - g_triggerStartTime));
      timerState = "Running: " + FormatElapsed(elapsed);
   }

   string display = StringFormat(
      "%s\nSymbol: %s\nTimeframe: %s\nRSI(%d): %.2f\nTrigger (going down): %.2f\nTrigger count: %I64d\nTimer: %s",
      g_eaTag,
      _Symbol,
      EnumToString(g_activeTimeframe),
      InpRSIPeriod,
      g_currentRsi,
      InpTriggerLevel,
      g_triggerCount,
      timerState
   );

   Comment(display);
}

int OnInit()
{
   if(!CreateRsiHandle())
      return(INIT_FAILED);

   EventSetTimer(1);
   UpdateChartDisplay();
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   EventKillTimer();

   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);

   Comment("");
}

void OnTick()
{
   if(InpRSITimeframe == PERIOD_CURRENT)
   {
      ENUM_TIMEFRAMES liveChartTf = (ENUM_TIMEFRAMES)Period();
      if(liveChartTf != g_activeTimeframe)
      {
         if(!CreateRsiHandle())
            return;
      }
   }

   RefreshRsiAndSignals();
   UpdateChartDisplay();
}

void OnTimer()
{
   RefreshRsiAndSignals();
   UpdateChartDisplay();
}
