#property copyright "Generated by Cursor Cloud Agent"
#property version   "1.00"
#property strict

input ENUM_TIMEFRAMES InpRSITimeframe = PERIOD_M15; // RSI calculation timeframe
input int             InpRSIPeriod    = 14;         // RSI period
input double          InpTriggerRSI   = 30.0;       // RSI trigger level (cross down)
input int             InpMultiStep    = 2;          // Confirmation steps: 2, 3, or 4
input bool            InpUsePush      = true;       // Send push notification
input bool            InpUsePopup     = true;       // Show terminal popup alert
input string          InpCustomTag    = "RSI EA";   // Tag in alert message

int      g_rsiHandle           = INVALID_HANDLE;
datetime g_lastClosedBarTime   = 0;
bool     g_sequenceActive      = false;
bool     g_waitingForReset     = false;
int      g_confirmedSteps      = 0;

bool IsValidMultiStep(int value)
{
   return (value == 2 || value == 3 || value == 4);
}

string TimeframeToString(ENUM_TIMEFRAMES tf)
{
   return EnumToString(tf);
}

void SendCrossdownAlert(double previousRsi, double currentRsi, int steps)
{
   string message = StringFormat(
      "%s | %s | RSI cross-down confirmed (%d/%d). TF=%s Trigger=%.2f Prev=%.2f Curr=%.2f",
      InpCustomTag,
      _Symbol,
      steps,
      InpMultiStep,
      TimeframeToString(InpRSITimeframe),
      InpTriggerRSI,
      previousRsi,
      currentRsi
   );

   if(InpUsePopup)
      Alert(message);

   if(InpUsePush)
   {
      if(!SendNotification(message))
         Print("SendNotification failed. Error: ", GetLastError());
   }

   Print(message);
}

bool GetRsiValues(double &rsiPrev2, double &rsiPrev1)
{
   double values[3];
   ArraySetAsSeries(values, true);

   if(CopyBuffer(g_rsiHandle, 0, 0, 3, values) < 3)
      return false;

   // values[1] = latest closed bar, values[2] = previous closed bar
   rsiPrev1 = values[1];
   rsiPrev2 = values[2];
   return true;
}

bool IsNewClosedBar()
{
   datetime closedBarTime = iTime(_Symbol, InpRSITimeframe, 1);
   if(closedBarTime <= 0)
      return false;

   if(closedBarTime == g_lastClosedBarTime)
      return false;

   g_lastClosedBarTime = closedBarTime;
   return true;
}

int OnInit()
{
   if(!IsValidMultiStep(InpMultiStep))
   {
      Print("Invalid InpMultiStep. Allowed values are 2, 3, or 4.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   if(InpRSIPeriod <= 0)
   {
      Print("InpRSIPeriod must be greater than 0.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   if(InpTriggerRSI < 0.0 || InpTriggerRSI > 100.0)
   {
      Print("InpTriggerRSI must be between 0 and 100.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   g_rsiHandle = iRSI(_Symbol, InpRSITimeframe, InpRSIPeriod, PRICE_CLOSE);
   if(g_rsiHandle == INVALID_HANDLE)
   {
      Print("Failed to create RSI handle. Error: ", GetLastError());
      return(INIT_FAILED);
   }

   Print("RSI Multistep Cross-down Alert EA initialized.");
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);
}

void OnTick()
{
   if(g_rsiHandle == INVALID_HANDLE)
      return;

   if(!IsNewClosedBar())
      return;

   double prev2 = 0.0, prev1 = 0.0;
   if(!GetRsiValues(prev2, prev1))
   {
      Print("Unable to read RSI buffer. Error: ", GetLastError());
      return;
   }

   // Unlock after RSI recovers above trigger, so a fresh cross-down can be detected.
   if(g_waitingForReset && prev1 > InpTriggerRSI)
      g_waitingForReset = false;

   if(g_waitingForReset)
      return;

   bool crossedDown = (prev2 > InpTriggerRSI && prev1 <= InpTriggerRSI);

   if(crossedDown)
   {
      g_sequenceActive = true;
      g_confirmedSteps = 1;
      return;
   }

   if(!g_sequenceActive)
      return;

   if(prev1 <= InpTriggerRSI)
   {
      g_confirmedSteps++;
      if(g_confirmedSteps >= InpMultiStep)
      {
         SendCrossdownAlert(prev2, prev1, g_confirmedSteps);
         g_sequenceActive  = false;
         g_waitingForReset = true;
         g_confirmedSteps  = 0;
      }
   }
   else
   {
      // Sequence invalidated because RSI moved back above trigger before confirmation.
      g_sequenceActive = false;
      g_confirmedSteps = 0;
   }
}
